apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tator
  region: us-east-2
managedNodeGroups:
  - name: cpuWorkers
    instanceType: m5.xlarge
    labels:
      cpuWorker: "yes"
      gpuWorker: "no"
      webServer: "yes"
      dbServer: "no"
    minSize: 1
    maxSize: 10
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: dbServers
    instanceType: r5.xlarge
    labels:
      cpuWorker: "no"
      gpuWorker: "no"
      webServer: "no"
      dbServer: "yes"
    minSize: 1
    maxSize: 10
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: gpuWorkers
    instanceType: p2.xlarge
    labels:
      cpuWorker: "no"
      gpuWorker: "yes"
      webServer: "no"
      dbServer: "no"
    minSize: 0
    maxSize: 1
    desiredCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
