apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-algorithm-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: user-algorithm
  policyTypes:
  - Ingress
  - Egress
