kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: static-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/static"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pv-claim
  labels:
    app: static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: upload-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: upload-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/upload"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: upload-pv-claim
  labels:
    app: upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: media-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: media-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/media"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pv-claim
  labels:
    app: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: raw-pv
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: raw-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/raw"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: raw-pv-claim
  labels:
    app: raw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgis-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/postgis"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-pv-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dev-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: dev-pv-claim
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: ${NFS_SERVER}
    path: "/media/kubernetes_share/dev"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pv-claim
  labels:
    app: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
