apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment
  labels:
    app: tusd
    type: web
spec:
  selector:
    matchLabels:
      app: tusd
      type: web
  replicas: 1
  template:
    metadata:
      labels:
        app: tusd
        type: web
    spec:
      nodeSelector:
        webServer: "yes"
      containers:
        - name: tusd
          image: ${DOCKERHUB_USER}/tator_tusd
          command: ["tusd"]
          args: ["-behind-proxy","-dir","/data/uploads"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1080
          volumeMounts:
            - mountPath: /data/uploads
              name: upload-pv-claim
      volumes:
        - name: upload-pv-claim
          persistentVolumeClaim:
            claimName: upload-pv-claim
