apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: migrate-flat-
spec:
  arguments:
    parameters:
    - name: sections
      value: |
        ["types", "media", "localizations", "states", "treeleaves", "analyses"]
  entrypoint: migrate-all
  templates:

  # Top level template
  - name: migrate-all
    steps:
    - - name: getprojects
        template: get-projects
    - - name: migrate-projects
        template: migrate-projects
        arguments:
          parameters:
          - name: projects
            value: "{{steps.getprojects.outputs.parameters.projects}}"
          - name: sections
            value: "{{workflow.parameters.sections}}"

  # Gets project IDs in a list and uses them as input to parallel for loop
  - name: get-projects
    container:
      image: "{{workflow.parameters.dockerRegistry}}/tator_online:{{workflow.parameters.version}}"
      command: [sh, -c]
      args: ["python3 manage.py getprojects > /projects.txt"]
      env:
      - name: DJANGO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: tator-secrets
            key: djangoSecretKey
      - name: POSTGRES_HOST
        value: "{{workflow.parameters.postgresHost}}"
      - name: POSTGRES_USERNAME
        value: "{{workflow.parameters.postgresUsername}}"
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tator-secrets
            key: postgresPassword
      - name: REDIS_HOST
        value: "{{workflow.parameters.redisHost}}"
      - name: ELASTICSEARCH_HOST
        value: "{{workflow.parameters.elasticsearchHost}}"
      - name: MAIN_HOST
        value: "{{workflow.parameters.domain}}"
      - name: TATOR_DEBUG
        value: "{{workflow.parameters.tatorDebug}}"
      - name: TATOR_USE_MIN_JS
        value: "{{workflow.parameters.useMinJs}}"
    outputs:
      parameters:
      - name: projects
        valueFrom:
          path: /projects.txt

  # Executes parallel for loop for list of projects
  - name: migrate-projects
    inputs:
      parameters:
      - name: projects
      - name: sections
    steps:
    - - name: migrate-project
        template: migrate-project
        arguments:
          parameters:
          - name: project
            value: "{{item}}"
          - name: sections
            value: "{{inputs.parameters.sections}}"
        withParam: "{{inputs.parameters.projects}}"

  # Executes sequential for loop for all sections on one project
  - name: migrate-project
    parallelism: 1
    inputs:
      parameters:
      - name: project
      - name: sections
    steps:
    - - name: migrate-section
        template: migrate-section
        arguments:
          parameters:
          - name: project
            value: "{{inputs.parameters.project}}"
          - name: section
            value: "{{item}}"
        withParam: "{{inputs.parameters.sections}}"

  # Builds indices for a given project and section
  - name: migrate-section
    retryStrategy:
      limit: 10
    inputs:
      parameters:
      - name: project
      - name: section
    container:
      image: "{{workflow.parameters.dockerRegistry}}/tator_online:{{workflow.parameters.version}}"
      command: ["python3"]
      args: ["manage.py", "migrateflat", "{{inputs.parameters.project}}", "{{inputs.parameters.section}}"]
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 1000m
          memory: 32Gi
      env:
      - name: DJANGO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: tator-secrets
            key: djangoSecretKey
      - name: POSTGRES_HOST
        value: "{{workflow.parameters.postgresHost}}"
      - name: POSTGRES_USERNAME
        value: "{{workflow.parameters.postgresUsername}}"
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tator-secrets
            key: postgresPassword
      - name: REDIS_HOST
        value: "{{workflow.parameters.redisHost}}"
      - name: ELASTICSEARCH_HOST
        value: "{{workflow.parameters.elasticsearchHost}}"
      - name: MAIN_HOST
        value: "{{workflow.parameters.domain}}"
      - name: TATOR_DEBUG
        value: "{{workflow.parameters.tatorDebug}}"
      - name: TATOR_USE_MIN_JS
        value: "{{workflow.parameters.useMinJs}}"
    
