apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: move-video-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: move_list # List of objects with src/dst.
                      # Example: [{"src": "/src/path", "dst": "/dst/path"}]
    - name: media_files 
    - name: media_id
    - name: host
    - name: token
  templates:
  - name: main
    steps:
    - - name: move-file
        template: move
        arguments:
          parameters:
          - name: src
            value: "{{item.src}}"
          - name: dst
            value: "{{item.dst}}"
        withParam: "{{workflow.parameters.move_list}}"
    - - name: patch-media
        template: patch
  - name: move
    inputs:
      parameters:
      - name: src
      - name: dst
    container:
      image: busybox:1.31.1-uclibc
      command: [mv]
      args: ["{{inputs.parameters.src}}", "{{inputs.parameters.dst}}"]
      resources:
        requests:
          memory: 128Mi
          cpu: 200m
  - name: patch
    container:
      image: curlimages/curl:7.71.0
      command: [curl]
      args: ["-H", "Content-Type: application/json", "-H", "Authorization: Token {{workflow.parameters.token}}", "-X", "PATCH", "-d", "{{workflow.parameters.media_files}}", "{{workflow.parameters.host}}/rest/Media/{{workflow.parameters.media_id}}"]
      resources:
        requests:
          memory: 64Mi
          cpu: 100m

