apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: move-video-
spec:
  entrypoint: main
  ttlStrategy:
    secondsAfterSuccess: 300
    secondsAfterFailure: 86400
  arguments:
    parameters:
    - name: wget_image
    - name: curl_image
    - name: move_list # List of objects with url, dst, upload_uid
    - name: media_update 
    - name: media_id
    - name: host
    - name: token
  volumes:
  - name: main-pv-claim
    persistentVolumeClaim:
      claimName: main-pv-claim
  templates:
  - name: main
    metadata:
      labels:
        app: move
    steps:
    - - name: move-file
        template: move
        arguments:
          parameters:
          - name: url
            value: "{{item.url}}"
          - name: dst
            value: "{{item.dst}}"
          - name: upload_uid
            value: "{{item.upload_uid}}"
        withParam: "{{workflow.parameters.move_list}}"
    - - name: patch-media
        template: patch
  - name: move
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      backoff:
        duration: "10"
        factor: 2
        maxDuration: "2h"
    inputs:
      parameters:
      - name: url
      - name: dst
      - name: upload_uid
    container:
      image: "{{workflow.parameters.wget_image}}"
      imagePullPolicy: IfNotPresent
      command: [wget]
      args: ["--header=Authorization: Token {{workflow.parameters.token}}",
             "--header=Upload-Uid: {{inputs.parameters.upload_uid}}",
             "-O", "{{inputs.parameters.dst}}",
             "{{inputs.parameters.url}}"]
      resources:
        requests:
          memory: 500Mi
          cpu: 250m
      volumeMounts:
      - mountPath: /uploads
        name: main-pv-claim
        subPath: upload
      - mountPath: /media
        name: main-pv-claim
        subPath: media
      - mountPath: /data/raw
        name: main-pv-claim
        subPath: raw
  - name: patch
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      backoff:
        duration: "10"
        factor: 2
        maxDuration: "2h"
    container:
      image: "{{workflow.parameters.curl_image}}"
      imagePullPolicy: IfNotPresent
      command: [curl]
      args: ["--retry", "5", "--connect-timeout", "5",
             "-H", "Content-Type: application/json",
             "-H", "Authorization: Token {{workflow.parameters.token}}",
             "-X", "PATCH",
             "-d", "{{workflow.parameters.media_update}}",
             "http://gunicorn-svc:8000/rest/Media/{{workflow.parameters.media_id}}"]
      resources:
        requests:
          memory: 500Mi
          cpu: 250m

