dockerRegistry: localhost:5000
nfsServer: 192.168.1.200
loadBalancerIp: 192.168.1.221
domain: debug.tatorapp.com
metallb:
  enabled: true
  ipRangeStart: 192.168.1.220
  ipRangeStop: 192.168.1.224
redis:
  enabled: true
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  usePassword: false
metrics-server:
  enabled: true
  args:
    - --v=2
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP
elasticsearch:
  enabled: true
  persistence:
    enabled: false
  replicas: 1
postgis:
  enabled: true
  hostPath: /media/kubernetes_share/postgis
nginxReplicas: 1
gunicornReplicas: 1
transcoderReplicas: 1
algorithmReplicas: 1
pv:
  staticSize: 1Gi
  uploadSize: 1Ti
  mediaSize: 4Ti
  rawSize: 6Ti
  postgisSize: 10Gi
  backupSize: 100Gi
  migrationsSize: 1Gi

