apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: algo-setup-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: algo-setup
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: nginx
