apiVersion: v1
kind: Service
metadata:
  name: gunicorn-svc
  labels:
    app: gunicorn
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: gunicorn-port
  selector:
    app: gunicorn
    type: web
  type: NodePort
