apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-internal-conf
data:
  nginx.conf: |
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      include mime.types;
      server_names_hash_bucket_size 128;
      proxy_ignore_client_abort on;

      {{ include "tusdProxy.upstream" . | indent 6 }}

      server {
        listen 80;

        server_name nginx-internal-svc;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        client_max_body_size 0;

        {{ include "tusdProxy.locations" . | indent 8 }}

        location /rest {
          # Allow for big REST responses.
          proxy_connect_timeout 1200;
          proxy_send_timeout 1200;
          proxy_read_timeout 1200;
          send_timeout 1200;

          proxy_pass http://gunicorn-svc:8000/rest;

          proxy_redirect off;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $server_name;
          add_header Cache-Control "max-age=0, must-revalidate";

          gzip on;
          gzip_types application/json;
          gzip_min_length 1024;
        }

        location / {
          return 404;
        }
      }
    }
