apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.hpa.nginxMinReplicas }}
  template:
    metadata:
      labels:
        app: nginx
      # Force nginx update whenever this file changes.
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
{{ if .Values.awsFargate.enabled }}
{{ else }}
      nodeSelector:
        webServer: "yes"
{{ end }}
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 4000m
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
              name: nginx-conf
            - mountPath: /ssl
              readOnly: true
              name: ssl
{{ if .Values.awsStorage.enabled }}
            - mountPath: /data/static
              name: efs-pv-claim
              subPath: static
            - mountPath: /data/media
              name: efs-pv-claim
              subPath: media
            - mountPath: /data/raw
              name: efs-pv-claim
              subPath: raw
{{ else }}
            - mountPath: /data/static
              name: static-pv-claim
            - mountPath: /data/media
              name: media-pv-claim
            - mountPath: /data/raw
              name: raw-pv-claim
{{ end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: ssl
          secret:
            secretName: tator-secrets
            items:
              - key: sslBundle
                path: CertificateBundle1.pem
              - key: sslKey
                path: tator.key
{{ if .Values.awsStorage.enabled }}
        - name: efs-pv-claim
          persistentVolumeClaim:
            claimName: efs-pv-claim
{{ else }}
        - name: static-pv-claim
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: media-pv-claim
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: raw-pv-claim
          persistentVolumeClaim:
            claimName: raw-pv-claim
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
{{- if .Values.metallb.enabled }}
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
{{- else }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
{{- end }}
spec:
{{- if .Values.metallb.enabled }}
  loadBalancerIP: {{ .Values.metallb.loadBalancerIp }}
{{- end }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
