
{{- $makeInitSettings := dict "Values" .Values "Release" .Release "Chart" .Chart "name" "make-init-py" "app" "make-init-py" "selector" "webServer: \"yes\"" "command" "[touch]" "args" "[\"/tator_online/main/migrations/__init__.py\"]" "hookWeight" "-1" "hook" "post-install" }}
{{ include "postjob.template" $makeInitSettings }}
---
{{- $makeMigrationsSettings := dict "Values" .Values "Release" .Release "Chart" .Chart "name" "make-migrations" "app" "make-migrations" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"makemigrations\"]" "hookWeight" "0" "hook" "post-install,post-upgrade" }}
{{ include "postjob.template" $makeMigrationsSettings }}
---
{{- $migrateSettings := dict "Values" .Values "Release" .Release "Chart" .Chart "name" "migrate" "app" "migrate" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"migrate\"]" "hookWeight" "1" "hook" "post-install,post-upgrade" }}
{{ include "postjob.template" $migrateSettings }}
---
{{- $collectStaticSettings := dict "Values" .Values "Release" .Release "Chart" .Chart "name" "collect-static" "app" "collect-static" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"collectstatic\", \"--noinput\"]" "hookWeight" "2" "post-install,post-upgrade" }}
{{ include "postjob.template" $collectStaticSettings }}
