{{ if .Values.pv.enabled }}
{{ if .Values.awsStorage.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: main-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.awsStorage.filesystemId }}
{{ else }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: main-pv
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: main-pv-claim
  mountOptions:
    {{- range .Values.pv.nfsMountOptions }}
    - {{ . }}
    {{- end }}
  nfs:
    server: {{ .Values.pv.nfsServer }}
    path: {{ .Values.pv.path }}
---
{{ if .Values.elasticsearch.enabled }}
{{ if .Values.elasticsearch.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: {{ $.Values.elasticsearch.volumeClaimTemplate.resources.requests.storage }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: elasticsearch-master-elasticsearch-master-0
  hostPath:
    path: {{ $.Values.elasticsearch.hostPath }}
{{ end }}
{{ end }}
---
{{ if .Values.postgis.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgis-pv
spec:
  capacity:
    storage: {{ $.Values.postgis.persistence.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgis-pv-claim
  hostPath:
    path: {{ $.Values.postgis.hostPath }}
{{ end }}
{{ end }} # .Values.awsStorage.enabled
{{ end }} # .Values.pv.enabled 
