{{ if .Values.awsStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
{{ else }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-pv-claim
  labels:
    app: static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{ if .Values.postgis.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-pv-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgis.persistence.size }}
{{ end }}
{{ end }}
