{{ if .Values.awsStorage.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: {{ .Values.awsStorage.ebs.type }}
  iopsPerGB: {{ .Values.awsStorage.ebs.iopsPerGb | quote }}
  fsType: ext4
  encrypted: "true"
{{ end }}
