
{{- $gunicornSettings := dict "Values" .Values "name" "gunicorn-deployment" "app" "gunicorn" "selector" "webServer: \"yes\""  "command" "[gunicorn]" "args" "[\"--workers\", \"3\", \"--worker-class=gevent\", \"--timeout\", \"600\",\"--reload\", \"-b\", \":8000\", \"tator_online.wsgi\"]" "init" "[echo]" "replicas" .Values.hpa.gunicornMinReplicas }}
{{include "tator.template" $gunicornSettings }}
---
{{- $daphneSettings := dict "Values" .Values "name" "daphne-deployment" "app" "daphne" "selector" "webServer: \"yes\""  "command" "[daphne]" "args" "[\"-b\", \"0.0.0.0\", \"-p\", \"8001\", \"tator_online.asgi:application\"]" "init" "[echo]" "replicas" .Values.hpa.daphneMinReplicas }}
{{include "tator.template" $daphneSettings }}
---
{{- $prunerSettings := dict "Values" .Values "name" "prune-messages-cron" "app" "pruner" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunemessages\"]" "schedule" "0 * * * *" }}
{{include "tatorCron.template" $prunerSettings }}
---
{{- $sizerSettings := dict "Values" .Values "name" "sizer-cron" "app" "sizer" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"updateprojects\"]" "schedule" "10 * * * *"  }}
{{include "tatorCron.template" $sizerSettings }}
---
{{- $tempSettings := dict "Values" .Values "name" "prune-temp-cron" "app" "prune-temp" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunetemporaryfiles\"]" "schedule" "20 * * * *" }}
{{include "tatorCron.template" $tempSettings }}
---
{{- $mediaSettings := dict "Values" .Values "name" "prune-media-cron" "app" "prune-media" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunemedia\"]" "schedule" "30 0 * * *" }}
{{include "tatorCron.template" $mediaSettings }}
---
{{- $localizationSettings := dict "Values" .Values "name" "prune-localizations-cron" "app" "prune-localizations" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunelocalizations\"]" "schedule" "30 1 * * *" }}
{{include "tatorCron.template" $localizationSettings }}
---
{{- $stateSettings := dict "Values" .Values "name" "prune-states-cron" "app" "prune-states" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunestates\"]" "schedule" "30 2 * * *" }}
{{include "tatorCron.template" $stateSettings }}
---
{{- $leafSettings := dict "Values" .Values "name" "prune-leaves-cron" "app" "prune-leaves" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"pruneleaves\"]" "schedule" "30 3 * * *" }}
{{include "tatorCron.template" $leafSettings }}

