
{{- $gunicornSettings := dict "Values" .Values "name" "gunicorn-deployment" "app" "gunicorn" "selector" "webServer: \"yes\""  "command" "[gunicorn]" "args" "[\"--workers\", \"1\", \"--worker-class=gevent\", \"--timeout\", \"600\",\"--reload\", \"-b\", \":8000\", \"tator_online.wsgi\"]" "init" "[echo]" "replicas" .Values.gunicornReplicas }}
{{include "tator.template" $gunicornSettings }}
---
{{- $daphneSettings := dict "Values" .Values "name" "daphne-deployment" "app" "daphne" "selector" "webServer: \"yes\""  "command" "[daphne]" "args" "[\"-b\", \"0.0.0.0\", \"-p\", \"8001\", \"tator_online.asgi:application\"]" "init" "[echo]" "replicas" "1" }}
{{include "tator.template" $daphneSettings }}
---
{{- $prunerSettings := dict "Values" .Values "name" "pruner-deployment" "app" "pruner" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"prunemessages\"]" "init" "[echo]" "replicas" "1" }}
{{include "tator.template" $prunerSettings }}
---
{{- $sizerSettings := dict "Values" .Values "name" "sizer-deployment" "app" "sizer" "selector" "webServer: \"yes\""  "command" "[python3]" "args" "[\"manage.py\", \"updateprojects\"]" "init" "[echo]" "replicas" "1" }}
{{include "tator.template" $sizerSettings }}

