apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment
  labels:
    app: tusd
    type: web
spec:
  selector:
    matchLabels:
      app: tusd
      type: web
  replicas: 1
  template:
    metadata:
      labels:
        app: tusd
        type: web
    spec:
      nodeSelector:
        webServer: "yes"
      containers:
        - name: tusd
          image: {{ .Values.dockerRegistry }}/tator_tusd
          command: ["tusd"]
          args: ["-behind-proxy","-upload-dir","/data/uploads"]
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 1080
          volumeMounts:
            - mountPath: /data/uploads
              name: upload-pv-claim
      volumes:
        - name: upload-pv-claim
          persistentVolumeClaim:
            claimName: upload-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tusd-svc
  labels:
    app: tusd
spec:
  ports:
  - name: tus
    port: 1080
    targetPort: 1080
  selector:
    app: tusd
    type: web
  type: NodePort
