apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nvidia-smi-
spec:
  entrypoint: printit
  ttlSecondsAfterFinished: 120
  templates:
  - name: printit
    container:
      image: nvidia/cuda
      resources:
        limits:
          nvidia.com/gpu: 1
      command: [nvidia-smi]
